/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const url = props.url;
  useGLTF.preload(url);
  const group = useRef();
  const { nodes, materials } = useGLTF(url);
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.text.geometry}
        material={materials["Material.002"]}
        position={[0, 0.25, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[-0.13, 0.13, 0.13]}
      />
      <mesh
        geometry={nodes.text001.geometry}
        material={materials["Material.001"]}
        position={[0, 0.13, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[-0.13, 0.13, 0.13]}
      />
      <mesh
        geometry={nodes.text002.geometry}
        material={materials["Material.001"]}
        position={[0, 0.02, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[-0.13, 0.13, 0.13]}
      />
    </group>
  );
}
